### ISSUE TITLE
Fire Notes to Mines?

### ISSUE THREAD

**Issue by GamingFan3926** [shockdude/fnf-to-sm#12]
If you try porting either Hellclown normal/hard or expurgation, You get an error because of the fire notes. Can you make it so they are replaced with mines, please? Thanks in advance!

**Comment by GamingFan3926** [comment]
For a better understanding, this is the log from when I ran FNF to SM to convert expurgation-hard.json to Expurgation.sm (I was able to retrieve this because I ran the script through command prompt):

Converting expurgation-hard.json to Expurgation.sm
Traceback (most recent call last):
  File "fnf-to-sm.py", line 404, in <module>
    main()
  File "fnf-to-sm.py", line 396, in main
    fnf_to_sm(infile)
  File "fnf-to-sm.py", line 187, in fnf_to_sm
    notes[tick][note] = 1
IndexError: list assignment index out of range
[9584] Failed to execute script fnf-to-sm

For reference, I converted blammed.json into Blammed.sm and it looks like this (again, I ran it in command prompt to retrieve the log):

Converting blammed.json to Blammed.sm
