### ISSUE TITLE
AttributeError: 'module' object has no attribute 'gcd'

### ISSUE THREAD

**Issue by TrafficConeYT** [shockdude/fnf-to-sm#14]
I am using this script on Linux Mint 20.1 (Ulyssa). 

When I try to use this script on my laptop, I get this (the command I am using is `python fnf-to-sm.py dadbattle.json`, and the json provided are from the week 7 update).

`Converting dadbattle.json to Dadbattle.sm
Traceback (most recent call last):
  File "fnf-to-sm.py", line 404, in <module>
    main()
  File "fnf-to-sm.py", line 396, in main
    fnf_to_sm(infile)
  File "fnf-to-sm.py", line 223, in fnf_to_sm
    noteStep = measure_gcd(valid_indexes, MEASURE_TICKS)
  File "fnf-to-sm.py", line 66, in measure_gcd
    d = math.gcd(d, x)
AttributeError: 'module' object has no attribute 'gcd'`

pls help idk what im doing
edit: this may not be important but forgot to mention the linux version i'm using has xcfe desktop not cinnamon

**Comment by TrafficConeYT** [comment]
Oops, nevermind I figured it out. I need to type `python3` instead of `python`. Sorry if I gave anyone an unnecessary notification.
