### ISSUE TITLE
doesnt support week 7 

### ISSUE THREAD

**Issue by arceuss** [shockdude/fnf-to-sm#7]
>fnf-to-sm.exe ugh.json
Traceback (most recent call last):
  File "fnf-to-sm.py", line 406, in <module>
  File "fnf-to-sm.py", line 398, in main
  File "fnf-to-sm.py", line 122, in fnf_to_sm
KeyError: 'notes'
[13096] Failed to execute script fnf-to-sm

**Comment by shockdude** [comment]
Fixed in v0.1.2
